import React, { Component } from 'react'
import Ite from "./ite"
import "./css/style.css"
export default class menu extends Component {
    constructor(props){
        super(props);
        this.state={
            dataList:[{
                img:'./imgs/1.jpg',
                fen:'来一份',
                title:"老北京杂酱面",
                con:"苏格兰打卤面，大杯可乐",
                price:'20',
                id:1
              },{
                img:'./imgs/2.jpg',
                fen:'来一份',
                title:"宫保鸡丁",
                con:"宫爆鸡丁一份,两份米饭,蛋花汤",
                price:'25',
                id:2
              },{
                img:'./imgs/3.jpg',
                fen:'来一份',
                title:"剁椒鱼头套餐",
                con:"剁椒鱼头,白菜豆腐汤，四碗面条，可口凉菜",
                price:'36',
                id:3
              },{
                img:'./imgs/4.jpg',
                fen:'来一份',
                title:"老北京烤鸭套餐",
                con:"北京烤鸭，四碗米饭，大杯可乐四桶，鸡蛋汤",
                price:'45',
                id:4
              },{
                img:'./imgs/6.jpg',
                fen:'来一份',
                title:"鱼香肉丝盖饭",
                con:"现炒鱼香肉丝",
                price:'15',
                id:5
              },{
                img:'./imgs/7.jpg',
                fen:'来一份',
                title:"尖椒肉丝盖饭",
                con:"绿色尖椒",
                price:'15',
                id:6
              },{
                img:'./imgs/8.jpg',
                fen:'来一份',
                title:"家常肉饼",
                con:"肉饼三个",
                price:'10',
                id:7
              },{
                img:'./imgs/9.jpg',
                fen:'来一份',
                title:"过油肉套餐",
                con:"过油肉一份，两碗米饭",
                price:'25',
                id:8
              },{
                img:'./imgs/10.jpg',
                fen:'来一份',
                title:"铁板牛柳套餐",
                con:"铁板牛柳一份，两碗米饭",
                price:'30',
                id:9
              },{
                img:'./imgs/11.jpg',
                fen:'来一份',
                title:"苦瓜炒蛋套餐",
                con:"苦瓜炒蛋一份，两碗米饭",
                price:'20',
                id:10
              },{
                img:'./imgs/13.jpg',
                fen:'来一份',
                title:"沙县木桶饭",
                con:"沙县红烧肉木桶饭",
                price:'18',
                id:11
              },{
                img:'./imgs/12.jpg',
                fen:'来一份',
                title:"兰州牛肉拉面",
                con:"兰州牛肉拉面大碗",
                price:'18',
                id:12
              },{
                img:'./imgs/14.jpg',
                fen:'来一份',
                title:"三明治咖啡套餐",
                con:"三明治两个，咖啡一杯",
                price:'15',
                id:13
              },{
                img:'./imgs/15.jpg',
                fen:'来一份',
                title:"意式香肠披萨",
                con:"7寸意式香肠一个",
                price:'56',
                id:14
              }]
        }
    }
    render() {
        let {dataList}=this.state
        return (
            <div className="gg">
                {dataList.map((item,index)=>{
                        return <Ite key={index} {...item}/> 
                    })}
            </div>
        )
    }
}
